- forest/core.py
Auxin semantics changed (not sure when) - this adds a bugfix for the json payload update, also now supports profile images.
> quick bugfix for profile updating

- forest/core.py
- mobfriend/Dockerfile
- mobfriend/mobfriend.py
Bumps Auxin version, documentation.
> Small fixups for MobFriend

- forest/payments_monitor.py
should fix some logging spam
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201632126650504/1201660992058410) by [Unito](https://www.unito.io)
> put connection and session in context managers

- CHANGELOG.md
- README.md
- forest/core.py
- forest/message.py
- forest/string_dist.py
refactor matching logic with is_admin and is_command + wait for timestamp on webhooks + uptime pretty
> better matching + extras

- forest/core.py
- forest/pdictng.py
files from id/hotlinev2, notably fixing remove bug Olivia ran into, adding increment and decrement calls to pdictng, moving questionbot to use uuid, adding uuid to is_admin, and adding better error handling to transaction sending.
> Rollup Hotline v2 "MOBot's Hotline" core/pdictng fixups

- forest/core.py
- forest/message.py
- mobfriend/mobfriend.py
QuestionBot uuids, better failed to build_transaction error handling, admin supports uuid, eval can access globals()
> MOBot Helper Fixups

- mobfriend/fly.toml
- mobfriend/mobfriend.py
> overdue fixes to helper

- full-service/Dockerfile
> Update upgrade path

- forest/core.py
also moves wait_resp -> wait_for_response
> small fix to pong semantics

- forest/core.py
Adds `do_challenge`, which serves as a basic captcha, and `ask_intable` / `ask_floatable` abstractions which prompt the user if an improperly formatted value is provided.
Also adds `require_first_device` flag to all `ask_` implementations, which will tell user to message from their phone if they aren't.
> QuestionBot Expansion

- forest/core.py
port fixes and expansions from the hotline; add signalme, rot13, recipients-store parsing, better error handling to sending payments
> Small fixes from Hotline

- forest/utils.py
fixes one of the problems in #131
> use socket.gethostname over /etc/hostname

- mobfriend/Dockerfile
- fix mobfriend dockerfile
- swap to signal-cli for real
> fix up mobfriend dockerfile

- hotline/hotline.py
Minimum viable fix for https://github.com/mobilecoinofficial/forest/issues/152
> Hotline: Send event owners blasts from other admins regardless if they're a list member or not 

- hotline/hotline.py
note that just setting ADMIN_GROUP (and dropping https://github.com/mobilecoinofficial/forest/blob/main/forest/core.py#L433 ` and not utils.AUXIN` once appropriate) does the thing we want
> quotable talkback

- pdictng_docs/README.md
> pdict-ng docs refresh

- forest/core.py
- forest/message.py
- sample_bots/evilbot.py
- add send_typing method
- update evilbot
> add send_typing

- forest/core.py
- forest/message.py
- add a bot that can track reply chains and reactions
- fix lints
- add sending quotes and a test command
- fix reactions
- revert stuff
- json
> to_dict base class so quotes get rendered right

- .github/workflows/checks.yml
- --dev
- bump cache
- revert --dev
> bump ci cache lock

- contact/contactbot.py
- forest/core.py
- forest/payments_monitor.py
- forest/pghelp.py
- mc_util/__init__.py
- add get_pmob_balance
- autocreate tables
- don't send a seperate message in handle_payment (need to check if anyone was relying on that)
> add get_pmob_balance, autocreate tables
